// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.28.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> writeTodolist({required List<TodoData> todolist, dynamic hint}) =>
    RustLib.instance.api.writeTodolist(todolist: todolist, hint: hint);

Future<List<TodoData>> getTodolist({dynamic hint}) =>
    RustLib.instance.api.getTodolist(hint: hint);

class TodoData {
  String id;
  final String description;
  final String startTime;
  final String endTime;

  TodoData({
    required this.id,
    required this.description,
    required this.startTime,
    required this.endTime,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      description.hashCode ^
      startTime.hashCode ^
      endTime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoData &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          description == other.description &&
          startTime == other.startTime &&
          endTime == other.endTime;
}
