name: "Display Tree"
on: workflow_dispatch

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          
      - run: flutter pub get

      - uses: dtolnay/rust-toolchain@stable

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - run: flutter build linux --release --verbose
      
      - name: Print directory tree
        run: tree build/linux/x64/release
        
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: build_linux
          path: build/linux/x64/release
          
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      
      - run: flutter pub get

      - uses: dtolnay/rust-toolchain@stable

      - run: flutter build macos --release --verbose
      
      - name: Install tree
        run: brew install tree
        
      - name: Print directory tree
        run: tree build/macos/Build/Products/Release
        
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: build_macos
          path: build/macos/Build/Products/Release
